#include <iostream>
#include <cstdlib>
#include <ctime>
#include <conio.h>
#include "player1.h"
#include "player2.h"
#include "PokemonCardsx.h"
#include "Ampharos.h"
#include "Blastoise.h"
#include "Charizard.h"
#include "Dragonite.h"
#include "Gardevoir.h"
#include "Gengar.h"
#include "Lucario.h"
#include "Metagross.h"
#include "Snorlax.h"
#include "Venusaur.h"
